# Generated by Django 4.2.7 on 2025-08-20 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='name',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='price_list', serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
